//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dkayit
    {
        public string kayitDosyaid { get; set; }
        public string kayitUyeid { get; set; }
        public string kayitDosyaturu { get; set; }
    
        public virtual Dosya Dosya { get; set; }
        public virtual Uye Uye { get; set; }

        public static implicit operator dkayit(HashSet<dkayit> v)
        {
            throw new NotImplementedException();
        }
    }
}
