//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dosya

    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dosya()
        {
            this.dkayit = new HashSet<dkayit>();
        }
    
    
        public string dosyaId { get; set; }
        public string dosyaAdi { get; set; }
        public string dosyaTuru { get; set; }
    
        public virtual dkayit dkayit { get; set; }
    }
}
